<?xml version="1.0" encoding="utf-8"?><Database Name="sample" Class="SampleClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SATHYAN\SQLEXPRESS;Initial Catalog=sample;Integrated Security=True" SettingsObjectName="LINQandSQL.Properties.Settings" SettingsPropertyName="sampleConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.department" Member="departments">
    <Type Name="department">
      <Column Name="deptno" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dname" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="department_Employee" Member="Employees" ThisKey="deptno" OtherKey="deptno" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="eno" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ename" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="deptno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="designation" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="department_Employee" Member="department" ThisKey="deptno" OtherKey="deptno" Type="department" IsForeignKey="true" />
    </Type>
  </Table>
</Database>